name: Manual OWASP Dependency Check

on:
  workflow_dispatch:  # Allows manual run from GitHub Actions tab


Owasp-dependency-check:
    runs-on: ubuntu-latest
    needs:  SonarCloud-check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download OWASP Dependency-Check CLI
        run: |
            curl -L -o dependency-check-12.1.6-release.zip https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.6/dependency-check-12.1.6-release.zip
            unzip dependency-check-12.1.6-release.zip
            chmod +x dependency-check/bin/dependency-check.sh




      - name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --project "MyProject" --scan . --format ALL --failOnCVSS 7


      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html
